### ISSUE TITLE
happy_onnx_modify.py 运行出错

### ISSUE THREAD

**Issue by yumendecc** [sesmfs/onnx_matcher#1]
你好，我尝试运行这个例程出现以下错误，能否帮忙看下是什么原因造成的？
Traceback (most recent call last):
  File "onnx_matcher/happy_onnx_modify.py", line 21, in <module>
    """
  File "onnx_matcher/onnx_matcher.py", line 242, in __init__
    self.lexer = Lexer(pattern)
  File "onnx_matcher/onnx_matcher.py", line 184, in __init__
    inputs, outputs = self.parse_arguments(argumants)
  File "onnx_matcher/onnx_matcher.py", line 233, in parse_arguments
    log(self.parse_list())
  File "onnx_matcher/onnx_matcher.py", line 220, in parse_list
    assert self.token == "]", f"Unexpected end token for list: ], pos: {self.itoken}"
AssertionError: Unexpected end token for list: ], pos: 9

**Comment by Tristannnnnnnnn** [comment]
我也是，请问你解决了吗？若解决了可否教教我？

**Comment by sesmfs** [comment]
Hi yumendecc and Healedtalk,

I have already fixed the bug and committed the changes to [#09889](https://github.com/sesmfs/onnx_matcher/commit/53373f8022828bb06360416caa6f48e500e09889). 

Thanks a lot.
